### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by nonetrix**
Updated the link because the repo must have been renamed at some point

# Description

Updated the link to Stackblitz so that it doesn't say it is wasn't found

## Type of change

- [✓] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I vised the link

# Checklist:

- [ ✓] I have performed a self-review of my own code

### CODE REVIEW

**Comment by nonetrix** [comment]
However, this code doesn't seem to work, but I will assume it's unrelated
image

**Comment by rodneylab** [comment]
Thanks for updating! Is code working for you with that change?

**Comment by nonetrix** [comment]
Somewhat, but error I got before is still there
```
~/projects/aonimoajj.github
❯ pnpm install && npm start
Lockfile is up to date, resolution step is skipped
Packages: +411
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 411, reused 0, downloaded 411, added 411, done

devDependencies:
+ @commitlint/config-conventional 17.6.6
+ @fontsource/playfair-display 5.0.4
+ @rodneylab/sveltekit-components 3.0.0
+ @sveltejs/kit 1.22.1
+ commitlint 17.6.6
+ eslint 8.44.0
+ eslint-config-prettier 8.8.0
+ eslint-plugin-svelte 2.32.2
+ husky 8.0.3
+ leaflet 1.9.4
+ postcss-html 1.5.0
+ prettier 2.8.8
+ prettier-plugin-svelte 2.10.1
+ stylelint 15.10.1
+ stylelint-config-recommended 13.0.0
+ svelte 4.0.5
+ svelte-check 3.4.5
+ vite 4.4.1

Done in 14.2s
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-07-08T00_17_53_862Z-debug-0.log
```

**Comment by rodneylab** [comment]
Thanks, that&rsquo;s really helpful. I have updated the StackBlitz config. Could I ask you to try once more? Thanks for your help!

**Comment by nonetrix** [comment]
image
Appears to be working somewhat

**Comment by rodneylab** [comment]
Thanks, I see that same error locally, when I first start the app in dev mode, but when I refresh the page, in browser, everything works fine.  Don't see the error in preview mode. Will take a closer look.

**Pull request merged**
